### ISSUE TITLE
Project requirements

### ISSUE THREAD

**Issue by abbasyazdinejad** [less-and-less-bugs/RDCM#1]
Hello,
Could you please give the details of the setup environment and project dependency to run the code?

**Comment by less-and-less-bugs** [comment]
Please  refer to the robust.yaml.

________________________________
From: Abbas Yazdinejad ***@***.***>
Sent: Thursday, November 30, 2023 12:48:34 AM
To: less-and-less-bugs/RDCM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [less-and-less-bugs/RDCM] Project requirements (Issue #1)


Hello,
Could you please give the details of the setup environment and project dependency to run the code?

―
