### ISSUE TITLE
pretrain_model

### ISSUE THREAD

**Issue by Hanhano1** [less-and-less-bugs/RDCM#2]
你好，很抱歉打扰您。我下载了预训练模型的压缩包并且已经解压了，也修改了路径，但是还是出现以下问题。麻烦告知一下训练模型的具体名称，以便到官网下载。谢谢！辛苦了！OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like roberta-base is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
root@autodl-container-703645b735-2cde4f80:~/autodl-tmp/FakeNews/RDCM-master#

**Comment by less-and-less-bugs** [comment]
This one: 

https://huggingface.co/FacebookAI/roberta-base 


Sorry for the delay. I am busy these days.

**Comment by less-and-less-bugs** [comment]
For the MMD implementation, I recommend you can use the codes of domainbed. Then you do not need to search parameters of kernels.
