### ISSUE TITLE
display_diff.py

### ISSUE THREAD

**Issue by summer832** [less-and-less-bugs/RDCM#3]
作者您好，请问可以公开一下测试时使用的display_diff.py文件吗？

**Comment by less-and-less-bugs** [comment]
不好意思，我没找到这个文件，请问你是在代码哪里看到这个文件的呢

**Comment by summer832** [comment]
您好！我是在[multi_our_model.sh]这个文件中看到有运行display_diff.py文件，
<img width="1127" alt="Snipaste_2024-06-27_14-08-28" src="https://github.com/less-and-less-bugs/RDCM/assets/71922812/c694f98d-12ad-44a2-8710-f6e740a9bd92">

**Comment by less-and-less-bugs** [comment]
emmmm, 不好意思，应该在我香港的服务器上，我现在在新加坡无法访问这台服务器，因为我们实验室没有vpn。实在抱歉。

**Comment by less-and-less-bugs** [comment]
这个文件是同一组参数，运行多次，report 方差和平均值，可以运行设置同一组参数，不同的随机种子，sh multi_out_model.sh多次，记录实验结果，最后计算方差和平均值。

**Comment by summer832** [comment]
好的好的，谢谢！
