### ISSUE TITLE
验证集划分

### ISSUE THREAD

**Issue by summer832** [less-and-less-bugs/RDCM#4]
作者您好，我看到您的论文中说在每个域中使用70%作为训练集，30%作为验证集，还有一个目标域作为测试集，但是我在您的代码中没有找到将源域分成训练集和验证集的部分，请问这个操作是在哪个地方做的呢？

**Comment by less-and-less-bugs** [comment]
Please find the dataset: download the dataset and pretrained models from Onedrive([datasets_pretrain_models.zip](https://portland-my.sharepoint.com/:u:/g/personal/liuhui3-c_my_cityu_edu_hk/ESqS-qpzsYJGoawSrzKDOlcBWr5e2plKA47L1JX0zsF4Ug?e=Gqu5Qi)) and unzip them in this project dir. The split operation is implemented using codes in this one drive link.
